# Generated by Django 3.0.3 on 2020-04-12 16:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantao', models.DateField(default=datetime.date.today)),
                ('turno', models.CharField(choices=[('1', 'Manhã'), ('2', 'Tarde'), ('3', 'Noite')], default='1', max_length=1)),
                ('horas', models.PositiveIntegerField()),
                ('plantonista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_plantao', 'turno'],
            },
        ),
    ]
