# Generated by Django 3.0.3 on 2020-04-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200415_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_active', 'first_name', 'last_name']},
        ),
    ]
